// SqlProxyClassGen: This code was auto-generated by a tool.
// Generated on 2023/02/10 11:24:13.
namespace CoinJar
{
    public partial class GetCoinJarResult
    {
        public System.Int32 CoinJarId { get; set; }
        public System.Decimal? Amount { get; set; }
        public System.Decimal? Volume { get; set; }

    }

}