// SqlProxyClassGen: This code was auto-generated by a tool and modified by another tool (Adrian)
    export class GetPlayerResult
    {
        PlayerId: number;
        FirstName: string;
        Surname: string;
        HeightInCm: number;
        DateOfBirth: string;
        TeamID: number;
        TeamName: string;
        StadiumId: number;
        StadiumName: string;
    }
    export class GetStadiumResult
    {
        StadiumId: number;
        Name: string;
        Location: string;
    }
    export class ListPlayersResult
    {
        PlayerId: number;
        FirstName: string;
        Surname: string;
        HeightInCm: number;
        DateOfBirth: string;
        TeamID: number;
        TeamName: string;
        StadiumId: number;
        StadiumName: string;
    }
    export class ListTeamsResult
    {
        TeamId: number;
        Name: string;
        StadiumId: number;
        StadiumName: string;
    }
    export class ListTransferHistoryResult
    {
        PlayerTransferHistoryId: number;
        PlayerId: number;
        FromTeamId: number;
        ToTeamId: number;
        TransferDate: string;
        FirstName: string;
        Surname: string;
        HeightInCm: number;
        DateOfBirth: string;
        TeamID: number;
        CurrentTeam: string;
        ToTeam: string;
        FromTeam: string;
    }
    export class ListStadiumsResult
    {
        StadiumId: number;
        Name: string;
        Location: string;
    }
