// SqlProxyClassGen: This code was auto-generated by a tool and modified by another tool (Adrian)
    export class GetCoinJarResult
    {
        CoinJarId: number;
        Amount: number;
        Volume: number;
    }
