// SqlProxyClassGen: This code was auto-generated by a tool.
// Generated on 2023/02/10 13:59:10.
namespace RugbyManagement
{
    public partial class GetPlayerResult
    {
        public System.Int32 PlayerId { get; set; }
        public System.String FirstName { get; set; }
        public System.String Surname { get; set; }
        public System.Decimal? HeightInCm { get; set; }
        public System.DateTime? DateOfBirth { get; set; }
        public System.Int32? TeamID { get; set; }
        public System.String TeamName { get; set; }
        public System.Int32? StadiumId { get; set; }
        public System.String StadiumName { get; set; }

    }
    public partial class GetStadiumResult
    {
        public System.Int32 StadiumId { get; set; }
        public System.String Name { get; set; }
        public System.String Location { get; set; }

    }
    public partial class GetTeamResult
    {
        public System.Int32 TeamId { get; set; }
        public System.String Name { get; set; }
        public System.Int32? StadiumId { get; set; }
        public System.String StadiumName { get; set; }

    }
    public partial class ListPlayersResult
    {
        public System.Int32 PlayerId { get; set; }
        public System.String FirstName { get; set; }
        public System.String Surname { get; set; }
        public System.Decimal? HeightInCm { get; set; }
        public System.DateTime? DateOfBirth { get; set; }
        public System.Int32? TeamID { get; set; }
        public System.String TeamName { get; set; }
        public System.Int32? StadiumId { get; set; }
        public System.String StadiumName { get; set; }

    }
    public partial class ListTeamsResult
    {
        public System.Int32 TeamId { get; set; }
        public System.String Name { get; set; }
        public System.Int32? StadiumId { get; set; }
        public System.String StadiumName { get; set; }

    }
    public partial class ListTransferHistoryResult
    {
        public System.Int32 PlayerTransferHistoryId { get; set; }
        public System.Int32? PlayerId { get; set; }
        public System.Int32? FromTeamId { get; set; }
        public System.Int32? ToTeamId { get; set; }
        public System.DateTime? TransferDate { get; set; }
        public System.String FirstName { get; set; }
        public System.String Surname { get; set; }
        public System.Decimal? HeightInCm { get; set; }
        public System.DateTime? DateOfBirth { get; set; }
        public System.Int32? TeamID { get; set; }
        public System.String CurrentTeam { get; set; }
        public System.String ToTeam { get; set; }
        public System.String FromTeam { get; set; }

    }
    public partial class ListStadiumsResult
    {
        public System.Int32 StadiumId { get; set; }
        public System.String Name { get; set; }
        public System.String Location { get; set; }

    }

}